#!/bin/bash

echo "Running post/postinst ..."

if [ ! -f /etc/default/minivtun ]; then
	mkdir -p /etc/default
	cat > /etc/default/minivtun <<EOF
#
vt_enabled=0
vt_network=go0
vt_server_addr=17.17.17.17
vt_server_port=8434
vt_password='WaWaWaWa'
vt_local_ipaddr=10.6.0.21
vt_local_netmask=255.255.255.0
vt_local_ip6pair=
vt_safe_dns=8.8.8.8
vt_safe_dns_port=53
vt_proxy_mode=S
# $covered_subnets, $local_addresses are not required
covered_subnets=192.168.10.0/24
local_addresses=192.168.10.1

EOF
fi

ln -svf ../init.d/minivtun.sh /etc/rc2.d/S95minivtun.sh
ln -svf ../init.d/minivtun.sh /etc/rc3.d/S95minivtun.sh
ln -svf ../init.d/minivtun.sh /etc/rc4.d/S95minivtun.sh
ln -svf ../init.d/minivtun.sh /etc/rc5.d/S95minivtun.sh

