#!/bin/bash

echo "Running post/postinst ..."

ln -svf ../init.d/ipset.sh /etc/rc2.d/S37ipset.sh
ln -svf ../init.d/ipset.sh /etc/rc3.d/S37ipset.sh
ln -svf ../init.d/ipset.sh /etc/rc4.d/S37ipset.sh
ln -svf ../init.d/ipset.sh /etc/rc5.d/S37ipset.sh

/etc/init.d/ipset.sh restart
